FileUploadTest/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fileapp.urls')),
]

fileapp/urls.py
from django.conf.urls import url
from . import views

app_name = 'fileapp'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^uploads/simple/$', views.simple_upload, name='simple_upload'),
    url(r'^search/$', views.search, name='search'),
]

fileapp/models.py
from django.db import models

class Employee(models.Model):
    Name = models.CharField(max_length=100)
    Email = models.EmailField()
    Phone_Number = models.PositiveIntegerField(blank=True)
    age = models.PositiveIntegerField(blank=True)


    def __str__(self):
        return '{} {}'.format(self.Name, self.Email)

fileapp/views.py
from django.shortcuts import render, redirect
from django.core.files.storage import FileSystemStorage
from fileapp.models import Employee
from django.db.models import Q
import xlrd
import datetime

def home(request):
    employees = Employee.objects.all()
    return render(request, 'fileapp/home.html', {'employees': employees})

def simple_upload(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        loc = ('D:\git projects\FileUploadTest\media\Interview File upload.xlsx')
        wb = xlrd.open_workbook(loc)
        sheet = wb.sheet_by_index(0)
        count = 0
        for i in range(1, sheet.nrows):
            emp_obj = []
            emp_obj.append(sheet.row_values(i))
            cell = sheet.cell(i, 3)
            value = cell.value
            if cell.ctype == 3:
                value = datetime.datetime(*xlrd.xldate_as_tuple(value, wb.datemode))

            emp_age = calculateAge(value)
            # print(type(emp_obj[0][2]), type(emp_age))
            emp = Employee(count, emp_obj[0][0], emp_obj[0][1], int(emp_obj[0][2]), emp_age)

            count += 1
            emp.save()


        uploaded_file_url = fs.url(filename)
        return render(request, 'fileapp/simple_upload.html', {
            'uploaded_file_url': uploaded_file_url
        })
    return render(request, 'fileapp/simple_upload.html')


def search(request, *args, **kwargs):
    if request.method == 'GET':
        employee_name = request.GET.get('Name')
        employee_email_id = request.GET.get('Email')
        employee_Phone_number = request.GET.get('Phone_Number')
        employee_age = request.GET.get('age')
        try:
            filters = Q(Q(Name__icontains=employee_name) & Q(Email__icontains=employee_email_id) & Q(Phone_Number__contains=employee_Phone_number) & Q(age__contains=employee_age))

            status = Employee.objects.filter(
                filters)
            print(status.query)
        except Employee.DoesNotExist:
            status = None
        return render(request, "fileapp/search.html", {"employees": status})
    else:
        return render(request, "fileapp/search.html", {})


def calculateAge(birthDate):
    today = datetime.date.today()
    Age = today.year - birthDate.year - ((today.month, today.day) < (birthDate.month, birthDate.day))

    return Age

fileapp/templates/fileapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Data System</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
        {% block body_block %}
    {% endblock %}

        <div>
            <ul>
                <li>
                    <a href="{% url 'fileapp:simple_upload' %}">Simple Upload</a>
                </li>

            </ul>
        </div>

             <form class="navbar-form navbar-left" method="GET" action="{% url 'fileapp:search' %}">
                 {% csrf_token %}
                <div class="form-group">
                    <label for="Name">Name:</label>
                    <input type="text" class="form-control" name="Name" placeholder="Name">
                    <p></p>
                    <label for="Email">Email:</label>
                    <input type="text" class="form-control" name="Email" placeholder="email">
                    <p></p>
                    <label for="Phone Number">Phone Number:</label>
                    <input type="text" class="form-control" name="Phone_Number" placeholder="number">
                    <p></p>
                    <label for="age">age:</label>
                    <input type="text" class="form-control" name="age" placeholder="age">

                </div>

                 <p></p>
                <button type="submit" class="btn btn-default">Submit</button>
             </form>




</body>
</html>

fileapp/templates/fileapp/home.html
{% extends 'fileapp/base.html' %}
{% block body_block %}
    <h3>This is the homepage for Data System</h3>
    <h3>Please choose among options for file upload or search</h3>
{% endblock %}

fileapp/templates/fileapp/search.html
{% extends 'fileapp/base.html' %}
{% block body_block %}
    {% if employees %}
    {% for each_employee in employees %}
        <li>{{each_student.Name}}, {{each_employee.Email}}, {{each_employee.Phone_Number}}, {{each_employee.age}}</li>

    {% endfor %}
    {% endif %}
{% endblock %}

fileapp/templates/fileapp/simple_upload.html
{% extends 'fileapp/base.html' %}
{% block body_block %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>

  {% if uploaded_file_url %}
    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  {% endif %}

  <p><a href="{% url 'fileapp:home' %}">Return to home</a></p>
{% endblock %}